// generated by Textmapper; DO NOT EDIT

#include "builder.h"
#include "tree.h"
#include "../json_lexer.h"
#include "../json_parser.h"
#include "selector.h"
#include "absl/functional/function_ref.h"
#include "absl/status/status.h"

#include <algorithm>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

namespace json {

// Forward declaration was in tree.h
// Builder class that implements the parser listener
class Builder {
 public:
  Builder(const std::string& path, const std::string& content)
      : tree_(path, content), stack_() {
    stack_.reserve(512);
  }

  void AddNode(json::NodeType type, json::NodeFlags flags, Lexer::Location loc) {
    size_t start = stack_.size();
    size_t end = start;

    while (start > 0 && stack_[start - 1]->offset_ >= loc.begin) {
      start--;
      if (stack_[start]->offset_ >= loc.end) {
        end--;
      }
    }

    // Create node directly (Builder is a friend of Node)
    Node* node_ptr = new Node(&tree_, type, loc.begin, loc.end);
    std::unique_ptr<Node> new_node(node_ptr);

    if (start < end) {
      node_ptr->firstChild_ = stack_[start].get();
      Node* prev = nullptr;
      for (size_t i = end; i > start;) {
        i--;
        Node* n = stack_[i].get();
        n->parent_ = node_ptr;
        n->next_ = prev;
        prev = n;
      }
    }

    if (end == stack_.size()) {
      stack_.resize(start);
      stack_.push_back(std::move(new_node));
    } else if (start < end) {
      stack_[start] = std::move(new_node);
      // Move elements from [end, stack_.size()) to [start+1, ...)
      size_t copy_len = stack_.size() - end;
      for (size_t i = 0; i < copy_len; i++) {
        if (start + 1 + i < stack_.size()) {
          stack_[start + 1 + i] = std::move(stack_[end + i]);
        } else {
          stack_.push_back(std::move(stack_[end + i]));
        }
      }
      stack_.resize(start + 1 + copy_len);
    } else {
      stack_.push_back(nullptr);
      // Shift elements from [start, stack_.size()-1) to [start+1, stack_.size())
      for (size_t i = stack_.size() - 1; i > start; i--) {
        stack_[i] = std::move(stack_[i - 1]);
      }
      stack_[start] = std::move(new_node);
    }
  }

  Tree Build() {
    if (stack_.size() != 1) {
      // Error: exactly one root node is expected
      // For now, we'll just set root to the first node if available
    }
    // Transfer ownership of nodes to the tree to keep them alive
    tree_.SetNodes(std::move(stack_));
    // Set root after moving nodes to ensure pointer is valid
    tree_.root_ = tree_.nodes_.empty() ? nullptr : tree_.nodes_[0].get();
    return std::move(tree_);
  }

 private:
  Tree tree_;
  std::vector<std::unique_ptr<Node>> stack_;
};

// Parse function implementation
Tree Parse(const std::string& path, const std::string& content, absl::FunctionRef<bool(absl::Status)> error_handler) {
  Builder builder(path, content);
  
  auto listener = [&builder](json::NodeType type, json::NodeFlags flags, Lexer::Location loc) {
    builder.AddNode(type, flags, loc);
  };
  
  
  Lexer lexer(content);
  Parser parser(listener, error_handler, false, 0, 0);
  (void)parser.Parse(lexer);
  
  return builder.Build();
}

}  // namespace json


