// generated by Textmapper; DO NOT EDIT

#ifndef EXAMPLES_JSON_AST_BUILDER_H_
#define EXAMPLES_JSON_AST_BUILDER_H_

#include <memory>
#include <string>

#include "tree.h"
#include "../json_lexer.h"
#include "../json_parser.h"
#include "absl/functional/function_ref.h"
#include "absl/status/status.h"

namespace json {

// Parse parses a given utf-8 content into an AST.
Tree Parse(const std::string& path, const std::string& content, absl::FunctionRef<bool(absl::Status)> error_handler);

// Convenience overload that parses content with an empty path.
inline Tree Parse(const std::string& content, absl::FunctionRef<bool(absl::Status)> error_handler) {
  return Parse("", content, error_handler);
}

// Convenience overload that parses content with default error handler (always recovers).
inline Tree Parse(const std::string& content) {
  auto error_handler = [](absl::Status) -> bool { return true; };
  return Parse("", content, error_handler);
}

}  // namespace json

#endif  // EXAMPLES_JSON_AST_BUILDER_H_


