// generated by Textmapper; DO NOT EDIT

#ifndef EXAMPLES_JSON_AST_SELECTOR_H_
#define EXAMPLES_JSON_AST_SELECTOR_H_

#include <functional>
#include <vector>

#include "../json_parser.h"

namespace json {

using Selector = std::function<bool(json::NodeType)>;

// Any selector matches all node types.
inline Selector Any = [](json::NodeType) -> bool { return true; };
// JSONArray selector matches JSONArray node type.
inline Selector JSONArray = [](json::NodeType t) -> bool {
  return t == json::NodeType::JSONArray;
};
// JSONEmptyObject selector matches JSONEmptyObject node type.
inline Selector JSONEmptyObject = [](json::NodeType t) -> bool {
  return t == json::NodeType::JSONEmptyObject;
};
// JSONMember selector matches JSONMember node type.
inline Selector JSONMember = [](json::NodeType t) -> bool {
  return t == json::NodeType::JSONMember;
};
// JSONObject selector matches JSONObject node type.
inline Selector JSONObject = [](json::NodeType t) -> bool {
  return t == json::NodeType::JSONObject;
};
// JSONText selector matches JSONText node type.
inline Selector JSONText = [](json::NodeType t) -> bool {
  return t == json::NodeType::JSONText;
};
// JSONValue selector matches JSONValue node type.
inline Selector JSONValue = [](json::NodeType t) -> bool {
  return t == json::NodeType::JSONValue;
};
// SyntaxProblem selector matches SyntaxProblem node type.
inline Selector SyntaxProblem = [](json::NodeType t) -> bool {
  return t == json::NodeType::SyntaxProblem;
};
// MultiLineComment selector matches MultiLineComment node type.
inline Selector MultiLineComment = [](json::NodeType t) -> bool {
  return t == json::NodeType::MultiLineComment;
};
// InvalidToken selector matches InvalidToken node type.
inline Selector InvalidToken = [](json::NodeType t) -> bool {
  return t == json::NodeType::InvalidToken;
};
// JSONString selector matches JSONString node type.
inline Selector JSONString = [](json::NodeType t) -> bool {
  return t == json::NodeType::JSONString;
};

// OneOf creates a selector that matches any of the given node types.
inline Selector OneOf(const std::vector<json::NodeType>& types) {
  if (types.empty()) {
    return [](json::NodeType) -> bool { return false; };
  }
  // Use a bitset for efficient lookup
  constexpr int bits = 32;
  int max = 1;
  for (json::NodeType t : types) {
    if (static_cast<int>(t) > max) {
      max = static_cast<int>(t);
    }
  }
  int size = (max + bits) / bits;
  std::vector<uint32_t> bitarr(size, 0);
  for (json::NodeType t : types) {
    int idx = static_cast<int>(t) / bits;
    bitarr[idx] |= 1U << (static_cast<int>(t) % bits);
  }
  return [bitarr](json::NodeType t) -> bool {
    int idx = static_cast<int>(t) / bits;
    return idx < static_cast<int>(bitarr.size()) &&
           (bitarr[idx] & (1U << (static_cast<int>(t) % bits))) != 0;
  };
}

// TokenSet selector matches any of the TokenSet category node types.
inline Selector TokenSet = OneOf(std::vector<json::NodeType>{ json::NodeType::JSONString });


}  // namespace json

#endif  // EXAMPLES_JSON_AST_SELECTOR_H_


