// generated by Textmapper; DO NOT EDIT

#include "json_lexer.h"
#include "json_token.h"

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/string_view.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/function.h>
#include <functional>
#include <memory>
#include <type_traits>

namespace nb = nanobind;
using namespace nb::literals;

namespace json {

// Bind Token enum
void bind_token(nb::module_ &m) {
  nb::enum_<Token>(m, "Token")
      .value("UNAVAILABLE", Token::UNAVAILABLE)
      .value("EOI", Token::EOI)
      .value("INVALID_TOKEN", Token::INVALID_TOKEN)
      .value("LBRACE", Token::LBRACE)
      .value("RBRACE", Token::RBRACE)
      .value("LBRACK", Token::LBRACK)
      .value("RBRACK", Token::RBRACK)
      .value("COLON", Token::COLON)
      .value("COMMA", Token::COMMA)
      .value("FOO", Token::FOO)
      .value("SPACE", Token::SPACE)
      .value("MULTILINECOMMENT", Token::MULTILINECOMMENT)
      .value("JSONSTRING", Token::JSONSTRING)
      .value("JSONNUMBER", Token::JSONNUMBER)
      .value("ID", Token::ID)
      .value("KW_NULL", Token::KW_NULL)
      .value("TRUE", Token::TRUE)
      .value("FALSE", Token::FALSE)
      .value("CHAR_A", Token::CHAR_A)
      .value("CHAR_B", Token::CHAR_B)
      .value("ERROR", Token::ERROR)
      .value("NumTokens", Token::NumTokens);
}

// Bind State enum
void bind_state(nb::module_ &m) {
  nb::enum_<Lexer::State>(m, "State")
      .value("Initial", Lexer::State::Initial)
      .value("Foo", Lexer::State::Foo)
      ;
}

// Wrapper to hold both the owned string and the Lexer.
// This is necessary to ensure that the std:string built by nanobind from the Python string is alive as long as the Lexer is alive. 
// An alternative would be to change the constructor of the Lexer to receive a std:string and copy it internally.
// It is better is to keep the Lexer receiving a absl::string_view.
struct LexerWrapper {
  std::string source_owned_;
  Lexer lexer;
  
  LexerWrapper(std::string s) 
    : source_owned_(std::move(s)),
      lexer(source_owned_) {}
};

// Bind Lexer class
void bind_lexer(nb::module_ &m) {
  nb::class_<LexerWrapper>(m, "Lexer")
      .def(nb::init<std::string>(), "input_source"_a)
      .def("next", [](LexerWrapper& w) { return w.lexer.Next(); }, "Find and return the next token in source")
      .def_prop_ro("begin", [](const LexerWrapper& w) { return w.lexer.token_offset_rune_; }, "Start offset of the current token in terms of utf-8 runes")
      .def_prop_ro("end", [](const LexerWrapper& w) { return w.lexer.offset_rune_; }, "End offset of the current token in terms of utf-8 runes")
      .def_prop_ro("line", [](const LexerWrapper& w) { return w.lexer.LastTokenLine(); }, "Line number of the last token (1-based)")
      .def_prop_ro("column", [](const LexerWrapper& w) { return w.lexer.LastTokenColumn(); }, "Column of the last token (in bytes, 1-based)")
      .def_prop_ro("text", [](const LexerWrapper& w) { return w.lexer.Text(); }, "Substring of the input corresponding to the last token");
}

// Location struct for Python (wraps Lexer::Location)
struct Location {
  int64_t begin;
  int64_t end;
  
  Location(int64_t b = 0, int64_t e = 0) : begin(b), end(e) {}
};

// Status wrapper for Python
struct StatusWrapper {
  absl::Status status;
  
  StatusWrapper(absl::Status s) : status(std::move(s)) {}
  
  bool ok() const { return status.ok(); }
  std::string message() const { return std::string(status.message()); }
};

}  // namespace json

NB_MODULE(nblexer, m) {
  m.doc() = "Python bindings for the json lexer and parser";
  
  json::bind_token(m);
  json::bind_state(m);
  json::bind_lexer(m);
}

