// generated by Textmapper; DO NOT EDIT

#include "json_lexer.h"
#include "json_parser.h"
#include "json_token.h"
#include "json_ast/tree.h"
#include "json_ast/builder.h"
#include "json_ast/selector.h"

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/string_view.h>
#include <nanobind/stl/tuple.h>
#include <nanobind/stl/function.h>
#include <functional>
#include <memory>
#include <type_traits>

namespace nb = nanobind;
using namespace nb::literals;

namespace json {

// Bind Token enum
void bind_token(nb::module_ &m) {
  nb::enum_<Token>(m, "Token")
      .value("UNAVAILABLE", Token::UNAVAILABLE)
      .value("EOI", Token::EOI)
      .value("INVALID_TOKEN", Token::INVALID_TOKEN)
      .value("LBRACE", Token::LBRACE)
      .value("RBRACE", Token::RBRACE)
      .value("LBRACK", Token::LBRACK)
      .value("RBRACK", Token::RBRACK)
      .value("COLON", Token::COLON)
      .value("COMMA", Token::COMMA)
      .value("FOO", Token::FOO)
      .value("SPACE", Token::SPACE)
      .value("MULTILINECOMMENT", Token::MULTILINECOMMENT)
      .value("JSONSTRING", Token::JSONSTRING)
      .value("JSONNUMBER", Token::JSONNUMBER)
      .value("ID", Token::ID)
      .value("KW_NULL", Token::KW_NULL)
      .value("TRUE", Token::TRUE)
      .value("FALSE", Token::FALSE)
      .value("CHAR_A", Token::CHAR_A)
      .value("CHAR_B", Token::CHAR_B)
      .value("ERROR", Token::ERROR)
      .value("NumTokens", Token::NumTokens);
}

// Bind State enum
void bind_state(nb::module_ &m) {
  nb::enum_<Lexer::State>(m, "State")
      .value("Initial", Lexer::State::Initial)
      .value("Foo", Lexer::State::Foo)
      ;
}

// Wrapper to hold both the owned string and the Lexer.
// This is necessary to ensure that the std:string built by nanobind from the Python string is alive as long as the Lexer is alive. 
// An alternative would be to change the constructor of the Lexer to receive a std:string and copy it internally.
// It is better is to keep the Lexer receiving a absl::string_view.
struct LexerWrapper {
  std::string source_owned_;
  Lexer lexer;
  
  LexerWrapper(std::string s) 
    : source_owned_(std::move(s)),
      lexer(source_owned_) {}
};

// Bind Lexer class
void bind_lexer(nb::module_ &m) {
  nb::class_<LexerWrapper>(m, "Lexer")
      .def(nb::init<std::string>(), "input_source"_a)
      .def("next", [](LexerWrapper& w) { return w.lexer.Next(); }, "Find and return the next token in source")
      .def_prop_ro("begin", [](const LexerWrapper& w) { return w.lexer.token_offset_rune_; }, "Start offset of the current token in terms of utf-8 runes")
      .def_prop_ro("end", [](const LexerWrapper& w) { return w.lexer.offset_rune_; }, "End offset of the current token in terms of utf-8 runes")
      .def_prop_ro("line", [](const LexerWrapper& w) { return w.lexer.LastTokenLine(); }, "Line number of the last token (1-based)")
      .def_prop_ro("column", [](const LexerWrapper& w) { return w.lexer.LastTokenColumn(); }, "Column of the last token (in bytes, 1-based)")
      .def_prop_ro("text", [](const LexerWrapper& w) { return w.lexer.Text(); }, "Substring of the input corresponding to the last token");
}

// Location struct for Python (wraps Lexer::Location)
struct Location {
  int64_t begin;
  int64_t end;
  
  Location(int64_t b = 0, int64_t e = 0) : begin(b), end(e) {}
};

// Status wrapper for Python
struct StatusWrapper {
  absl::Status status;
  
  StatusWrapper(absl::Status s) : status(std::move(s)) {}
  
  bool ok() const { return status.ok(); }
  std::string message() const { return std::string(status.message()); }
};

// Parser wrapper that handles Python callbacks
struct ParserWrapper {
  std::function<void(NodeType, int, Location)> listener;
  std::function<bool(StatusWrapper)> error_handler;
  int x_val;
  bool y_val;
  // Store callbacks as member variables to keep them alive for absl::FunctionRef
  std::function<void(NodeType, NodeFlags, Lexer::Location)> listener_adapter;
  std::function<bool(absl::Status)> error_adapter;
  std::unique_ptr<Parser> parser;
  
  ParserWrapper(
      std::function<void(NodeType, int, Location)> listener_func,
      std::function<bool(StatusWrapper)> error_handler_func,
      bool byteLocation,
      int x_arg,
      bool y_arg)
    : listener(std::move(listener_func)),
      error_handler(std::move(error_handler_func)),
      x_val(x_arg),
      y_val(y_arg) {
    // Create adapter callbacks and store them as members
    // Convert NodeFlags to int to handle bitfield combinations
    listener_adapter = [this](NodeType node, NodeFlags flags, Lexer::Location loc) {
      Location py_loc{loc.begin, loc.end};
      listener(node, static_cast<int>(flags), py_loc);
    };
    
    error_adapter = [this](absl::Status status) -> bool {
      StatusWrapper wrapped_status(std::move(status));
      return error_handler(wrapped_status);
    };
    
    parser = std::make_unique<Parser>(
        listener_adapter,
        error_adapter,
        byteLocation,
        x_val,
        y_val);
  }
  
  StatusWrapper parse(LexerWrapper& lexer_wrapper) {
    return StatusWrapper(parser->Parse(lexer_wrapper.lexer));
  }
};

// Bind NodeType enum
void bind_node_type(nb::module_ &m) {
  nb::enum_<NodeType>(m, "NodeType")
      .value("NoType", NodeType::NoType)
      .value("JSONArray", NodeType::JSONArray)
      .value("JSONEmptyObject", NodeType::JSONEmptyObject)
      .value("JSONMember", NodeType::JSONMember)
      .value("JSONObject", NodeType::JSONObject)
      .value("JSONText", NodeType::JSONText)
      .value("JSONValue", NodeType::JSONValue)
      .value("SyntaxProblem", NodeType::SyntaxProblem)
      .value("MultiLineComment", NodeType::MultiLineComment)
      .value("InvalidToken", NodeType::InvalidToken)
      .value("JSONString", NodeType::JSONString)
      .value("NodeTypeMax", NodeType::NodeTypeMax);
}

// Bind NodeFlags enum (bitfield flags)
void bind_node_flags(nb::module_ &m) {
  nb::enum_<NodeFlags>(m, "NodeFlags", nb::is_arithmetic())
      .value("None", NodeFlags::None)
      .value("Bar", NodeFlags::Bar)
      .value("Foo", NodeFlags::Foo)
      ;
}

// Bind Parser class
void bind_parser(nb::module_ &m) {
  nb::class_<Location>(m, "Location")
      .def(nb::init<int64_t, int64_t>(), "begin"_a = 0, "end"_a = 0)
      .def_ro("begin", &Location::begin)
      .def_ro("end", &Location::end);
  
  nb::class_<StatusWrapper>(m, "Status")
      .def_prop_ro("ok", &StatusWrapper::ok)
      .def_prop_ro("message", &StatusWrapper::message);
  
  nb::class_<ParserWrapper>(m, "Parser")
      .def(nb::init<
          std::function<void(NodeType, int, Location)>,
          std::function<bool(StatusWrapper)>,
          bool,
          int,
          bool>(),
          "listener"_a, "error_handler"_a, "byteLocation"_a = false, "x"_a, "y"_a)
      .def("parse", &ParserWrapper::parse, "lexer"_a);
}

// Bind Tree and Node classes, and parse function
void bind_ast(nb::module_ &m) {
  // Bind Node class
  nb::class_<Node>(m, "Node")
      .def_prop_ro("type", &Node::Type)
      .def("offset", &Node::Offset, "Returns the start offset of the node")
      .def("endoffset", &Node::Endoffset, "Returns the end offset of the node")
      .def("is_valid", &Node::IsValid, "Checks if the node is valid")
      .def("get_tree", &Node::GetTree, "Returns the tree containing this node", nb::rv_policy::reference_internal)
      .def("line_column", &Node::LineColumn, "Returns the start position as (line, column)")
      .def("text", &Node::Text, "Returns the text content of the node")
      .def("child", [](const Node& n, nb::object sel_obj) {
        // Convert Python callable to Selector
        nb::object sel_obj_copy = sel_obj;  // Ensure proper capture
        Selector sel = [sel_obj_copy](NodeType nt) -> bool {
          try {
            nb::object result = sel_obj_copy(nb::cast(nt));
            return nb::cast<bool>(result);
          } catch (...) {
            return false;
          }
        };
        return n.Child(sel);
      }, "sel"_a, "Returns the first child matching the selector", nb::rv_policy::reference_internal)
      .def("children", [](const Node& n, nb::object sel_obj) {
        // Convert Python callable to Selector
        nb::object sel_obj_copy = sel_obj;  // Ensure proper capture
        Selector sel = [sel_obj_copy](NodeType nt) -> bool {
          try {
            nb::object result = sel_obj_copy(nb::cast(nt));
            return nb::cast<bool>(result);
          } catch (...) {
            return false;
          }
        };
        return n.Children(sel);
      }, "sel"_a, "Returns all children matching the selector")
      .def("next", [](const Node& n, nb::object sel_obj) {
        // Convert Python callable to Selector
        nb::object sel_obj_copy = sel_obj;  // Ensure proper capture
        Selector sel = [sel_obj_copy](NodeType nt) -> bool {
          try {
            nb::object result = sel_obj_copy(nb::cast(nt));
            return nb::cast<bool>(result);
          } catch (...) {
            return false;
          }
        };
        return n.Next(sel);
      }, "sel"_a, "Returns the first right sibling matching the selector", nb::rv_policy::reference_internal)
      .def("next_all", [](const Node& n, nb::object sel_obj) {
        // Convert Python callable to Selector
        nb::object sel_obj_copy = sel_obj;  // Ensure proper capture
        Selector sel = [sel_obj_copy](NodeType nt) -> bool {
          try {
            nb::object result = sel_obj_copy(nb::cast(nt));
            return nb::cast<bool>(result);
          } catch (...) {
            return false;
          }
        };
        return n.NextAll(sel);
      }, "sel"_a, "Returns all right siblings matching the selector")
      ;
  
  // Bind Tree class (non-copyable, return by value with move semantics)
  nb::class_<Tree>(m, "Tree")
      .def_prop_ro("path", &Tree::Path, "Returns the location of the parsed content")
      .def_prop_ro("root", &Tree::Root, "Returns the root node", nb::rv_policy::reference_internal)
      .def_prop_ro("text", &Tree::Text, "Returns the parsed content")
      .def("line_column", &Tree::LineColumn, "offset"_a, "Returns the position as (line, column) for the given offset")
      ;
  
  // Bind parse function (with path and content)
  using ErrorHandler = std::function<bool(StatusWrapper)>;
  // Overload without error_handler (uses default that always recovers)
  m.def("parse", [](const std::string& content) {
    return Parse(content);
  }, "content"_a, "Parse json input and return an AST Tree", nb::rv_policy::move);
  // Overload with error_handler
  m.def("parse", [](const std::string& content, ErrorHandler eh) {
    auto error_handler = [eh](absl::Status status) -> bool {
      return eh(StatusWrapper(status));
    };
    return Parse("", content, error_handler);
  }, "content"_a, "error_handler"_a, "Parse json input and return an AST Tree", nb::rv_policy::move);
}

// Bind ast submodule (exposes NodeType enum values)
void bind_ast_submodule(nb::module_ &m) {
  auto ast = m.def_submodule("ast", "AST node types");
  ast.attr("NoType") = NodeType::NoType;
  ast.attr("JSONArray") = NodeType::JSONArray;
  ast.attr("JSONEmptyObject") = NodeType::JSONEmptyObject;
  ast.attr("JSONMember") = NodeType::JSONMember;
  ast.attr("JSONObject") = NodeType::JSONObject;
  ast.attr("JSONText") = NodeType::JSONText;
  ast.attr("JSONValue") = NodeType::JSONValue;
  ast.attr("SyntaxProblem") = NodeType::SyntaxProblem;
  ast.attr("MultiLineComment") = NodeType::MultiLineComment;
  ast.attr("InvalidToken") = NodeType::InvalidToken;
  ast.attr("JSONString") = NodeType::JSONString;
  ast.attr("NodeTypeMax") = NodeType::NodeTypeMax;
  // NonExistingType is a dummy value for testing - it doesn't exist in the enum
  // Expose it as an integer that won't match any real node type
  // When compared in Python tests, it will be compared as int vs NodeType enum
  ast.attr("NonExistingType") = static_cast<int>(NodeType::NodeTypeMax) + 1;
}

// Bind selector submodule (exposes selector functions)
void bind_selector_submodule(nb::module_ &m) {
  auto selector = m.def_submodule("selector", "AST node selectors");
  // Expose selectors as Python callable objects
  // They will be converted to Selector type when passed to Node methods
  selector.def("Any", [](NodeType nt) -> bool { return json::Any(nt); });
  selector.def("JSONArray", [](NodeType nt) -> bool { return json::JSONArray(nt); });
  selector.def("JSONEmptyObject", [](NodeType nt) -> bool { return json::JSONEmptyObject(nt); });
  selector.def("JSONMember", [](NodeType nt) -> bool { return json::JSONMember(nt); });
  selector.def("JSONObject", [](NodeType nt) -> bool { return json::JSONObject(nt); });
  selector.def("JSONText", [](NodeType nt) -> bool { return json::JSONText(nt); });
  selector.def("JSONValue", [](NodeType nt) -> bool { return json::JSONValue(nt); });
  selector.def("SyntaxProblem", [](NodeType nt) -> bool { return json::SyntaxProblem(nt); });
  selector.def("MultiLineComment", [](NodeType nt) -> bool { return json::MultiLineComment(nt); });
  selector.def("InvalidToken", [](NodeType nt) -> bool { return json::InvalidToken(nt); });
  selector.def("JSONString", [](NodeType nt) -> bool { return json::JSONString(nt); });
  selector.def("TokenSet", [](NodeType nt) -> bool { return json::TokenSet(nt); });
  // Bind OneOf function
  selector.def("OneOf", [](const std::vector<NodeType>& types) -> nb::object {
    Selector sel = json::OneOf(types);
    // Return as a Python callable
    return nb::cast(sel);
  }, "types"_a, "Create a selector that matches any of the given node types");
}

}  // namespace json

NB_MODULE(nblexer, m) {
  m.doc() = "Python bindings for the json lexer and parser";
  
  json::bind_token(m);
  json::bind_state(m);
  json::bind_lexer(m);
  json::bind_node_type(m);
  json::bind_node_flags(m);
  json::bind_parser(m);
  json::bind_ast(m);
  json::bind_ast_submodule(m);
  json::bind_selector_submodule(m);
}

